<?php 
/**
 * Cronjob Scheduler Include File
 *
 * This page allows you to create Cronjob Scheduler custom actions
 * through the WordPress admin. Actions can also be created within
 * theme files or other PHP files throughout your WordPress install.
 *
 * Do not edit this file unless you have a good understanding of PHP, 
 * saving this with invalid code can render your WordPress install inoperable
 * until you can fix the issue using FTP or another file editing utility.
**/

function my_cronjob_action () {
$destinatario = "maxifalcone@gmail.com"; 
$asunto = "Este mensaje es de prueba"; 
$cuerpo = ' 
<html> 
<head> 
   <title>Prueba de correo</title> 
</head> 
<body> 
<h1>Hola amigos!</h1> 
<p> 
<b>Bienvenidos a mi correo electrónico de prueba</b>. Estoy encantado de tener tantos lectores. Este cuerpo del mensaje es del artículo de envío de mails por PHP. Habría que cambiarlo para poner tu propio cuerpo. Por cierto, cambia también las cabeceras del mensaje. 
</p> 
</body> 
</html> 
'; 

//para el envío en formato HTML 
$headers = "MIME-Version: 1.0\r\n"; 
$headers .= "Content-type: text/html; charset=iso-8859-1\r\n"; 

//dirección del remitente 
$headers .= "From: Miguel Angel Alvarez <maximilianofalcone@ciudadfutura.com.ar>\r\n"; 

//dirección de respuesta, si queremos que sea distinta que la del remitente 
$headers .= "Reply-To: mariano@desarrolloweb.com\r\n"; 

//ruta del mensaje desde origen a destino 
$headers .= "Return-path: holahola@desarrolloweb.com\r\n"; 

mail($destinatario,$asunto,$cuerpo,$headers) ;

    // code to execute on cron run
} add_action('my_cronjob_action', 'my_cronjob_action');
